import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { ArrowRight, Pencil, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/PageHeader";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { supabase } from "@/integrations/supabase/client";
import { accountsQuery, friendlyError, incomeEntriesQuery, transactionsQuery, transfersQuery, useInvalidateData, type Account, type Transfer } from "@/lib/data";
import { accountTotals } from "@/lib/engine";
import { dateLabel, formatMoney, todayISO } from "@/lib/format";
import { profileQuery } from "@/lib/profile";

export const Route = createFileRoute("/_authenticated/_app/accounts")({ head: () => ({ meta: [{ title: "Accounts — Halal Budget Planner" }, { name: "description", content: "Account balances, minimums and transfers." }, { property: "og:title", content: "Accounts — Halal Budget Planner" }, { property: "og:description", content: "Account balances, minimums and transfers." }] }), component: AccountsPage });

function AccountsPage() {
  const { data: profile } = useQuery(profileQuery); const { data: accounts = [] } = useQuery(accountsQuery); const { data: income = [] } = useQuery(incomeEntriesQuery); const { data: transactions = [] } = useQuery(transactionsQuery); const { data: transfers = [] } = useQuery(transfersQuery); const invalidate = useInvalidateData(); const cur = profile?.currency ?? "USD";
  const totals = accountTotals(accounts.map((a) => ({ ...a, opening_balance: Number(a.opening_balance), minimum_balance: Number(a.minimum_balance), actual_balance: a.actual_balance == null ? null : Number(a.actual_balance) })), income, transactions, transfers);
  const [accountEdit, setAccountEdit] = useState<Account | "new" | null>(null); const [transferEdit, setTransferEdit] = useState<Transfer | "new" | null>(null); const names = useMemo(() => new Map(accounts.map((a) => [a.id, a.name])), [accounts]);
  async function removeAccount(a: Account) { if (!confirm(`Delete account "${a.name}"? Related entries will keep their amounts but lose the account.`)) return; const { error } = await supabase.from("accounts").delete().eq("id", a.id); if (error) return toast.error(friendlyError(error)); invalidate(); }
  async function removeTransfer(t: Transfer) { if (!confirm("Delete this transfer?")) return; const { error } = await supabase.from("transfers").delete().eq("id", t.id); if (error) return toast.error(friendlyError(error)); invalidate(); }
  return <><PageHeader eyebrow="Where money lives" title="Accounts" actions={<Button variant="secondary" size="sm" onClick={() => setAccountEdit("new")} disabled={accounts.length >= 10}><Plus /> Add account</Button>} /><main className="relative mx-auto -mt-6 flex max-w-6xl flex-col gap-5 px-5 pb-24 md:px-10">
    {totals.length === 0 ? <Empty text="Add an account to see its calculated and usable balance." /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{totals.map((t) => <article key={t.account.id} className="rounded-3xl border bg-card p-5 shadow-soft"><div className="flex justify-between gap-3"><div><p className="text-xs uppercase text-muted-foreground">Available balance</p><h2 className="mt-1 text-xl">{t.account.name}</h2></div><div className="flex"><Button size="icon" variant="ghost" aria-label={`Edit ${t.account.name}`} onClick={() => setAccountEdit(accounts.find((a) => a.id === t.account.id) ?? null)}><Pencil /></Button><Button size="icon" variant="ghost" className="hover:text-destructive" aria-label={`Delete ${t.account.name}`} onClick={() => { const a = accounts.find((x) => x.id === t.account.id); if (a) removeAccount(a); }}><Trash2 /></Button></div></div><p className="mt-4 text-2xl font-bold">{formatMoney(t.balance, cur)}</p><div className="mt-4 grid grid-cols-2 gap-3"><Metric label="Calculated" value={formatMoney(t.calculated, cur)} /><Metric label="Actual" value={t.account.actual_balance == null ? "Not entered" : formatMoney(t.account.actual_balance, cur)} /><Metric label="Difference" value={t.difference == null ? "—" : formatMoney(t.difference, cur)} /><Metric label="Minimum" value={formatMoney(t.account.minimum_balance, cur)} /></div><div className="mt-4 rounded-2xl bg-secondary p-3"><p className="text-xs text-secondary-foreground">Usable above minimum</p><p className="font-bold text-secondary-foreground">{formatMoney(t.usable, cur)}</p></div></article>)}</div>}
    <section className="rounded-3xl border bg-card p-5 shadow-soft"><div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="text-lg">Transfers</h2><p className="text-xs text-muted-foreground">Move money between your accounts.</p></div><Button size="sm" onClick={() => setTransferEdit("new")} disabled={accounts.length < 2}><Plus /> Add transfer</Button></div>{transfers.length === 0 ? <p className="rounded-2xl bg-muted p-6 text-center text-sm text-muted-foreground">No transfers yet.</p> : <ul>{transfers.map((t) => <li key={t.id} className="flex items-center gap-3 border-t py-3 first:border-t-0"><div className="min-w-0 flex-1"><div className="flex items-center gap-2 font-medium"><span>{t.from_account_id ? names.get(t.from_account_id) ?? "Unknown" : "Unknown"}</span><ArrowRight className="size-4 text-muted-foreground" /><span>{t.to_account_id ? names.get(t.to_account_id) ?? "Unknown" : "Unknown"}</span></div><p className="text-xs text-muted-foreground">{dateLabel(t.date)}{t.note ? ` · ${t.note}` : ""}</p></div><strong>{formatMoney(Number(t.amount), cur)}</strong><Button size="icon" variant="ghost" aria-label="Edit transfer" onClick={() => setTransferEdit(t)}><Pencil /></Button><Button size="icon" variant="ghost" className="hover:text-destructive" aria-label="Delete transfer" onClick={() => removeTransfer(t)}><Trash2 /></Button></li>)}</ul>}</section>
  </main><Dialog open={accountEdit != null} onOpenChange={(o) => !o && setAccountEdit(null)}><DialogContent><DialogHeader><DialogTitle>{accountEdit === "new" ? "Add account" : "Edit account"}</DialogTitle></DialogHeader>{accountEdit && <AccountForm initial={accountEdit === "new" ? undefined : accountEdit} accounts={accounts} onDone={() => setAccountEdit(null)} />}</DialogContent></Dialog><Dialog open={transferEdit != null} onOpenChange={(o) => !o && setTransferEdit(null)}><DialogContent><DialogHeader><DialogTitle>{transferEdit === "new" ? "Add transfer" : "Edit transfer"}</DialogTitle></DialogHeader>{transferEdit && <TransferForm initial={transferEdit === "new" ? undefined : transferEdit} accounts={accounts} onDone={() => setTransferEdit(null)} />}</DialogContent></Dialog></>;
}

function AccountForm({ initial, accounts, onDone }: { initial?: Account; accounts: Account[]; onDone: () => void }) { const invalidate = useInvalidateData(); const [name, setName] = useState(initial?.name ?? ""); const [opening, setOpening] = useState(String(initial?.opening_balance ?? 0)); const [minimum, setMinimum] = useState(String(initial?.minimum_balance ?? 0)); const [actual, setActual] = useState(initial?.actual_balance == null ? "" : String(initial.actual_balance)); async function save() { const clean = name.trim(); const op = Number(opening), min = Number(minimum), act = actual === "" ? null : Number(actual); if (!clean || clean.length > 30) return toast.error("Enter an account name up to 30 characters."); if (accounts.some((a) => a.id !== initial?.id && a.name === clean)) return toast.error("That account name is already used."); if (![op, min].every(Number.isFinite) || min < 0 || (act != null && !Number.isFinite(act))) return toast.error("Check the account amounts."); const row = { name: clean, opening_balance: op, minimum_balance: min, actual_balance: act }; const { error } = initial ? await supabase.from("accounts").update(row).eq("id", initial.id) : await supabase.from("accounts").insert(row); if (error) return toast.error(friendlyError(error)); invalidate(); onDone(); } return <div className="grid gap-3"><Field label="Name"><Input value={name} maxLength={30} onChange={(e) => setName(e.target.value)} autoFocus /></Field><Field label="Opening balance"><Input type="number" step="0.01" value={opening} onChange={(e) => setOpening(e.target.value)} /></Field><Field label="Minimum balance"><Input type="number" min="0" step="0.01" value={minimum} onChange={(e) => setMinimum(e.target.value)} /></Field><Field label="Actual balance"><Input type="number" step="0.01" value={actual} onChange={(e) => setActual(e.target.value)} placeholder="Optional" /></Field><Button onClick={save}>{initial ? "Save changes" : "Add account"}</Button></div>; }

function TransferForm({ initial, accounts, onDone }: { initial?: Transfer; accounts: Account[]; onDone: () => void }) { const invalidate = useInvalidateData(); const [from, setFrom] = useState(initial?.from_account_id ?? accounts[0]?.id ?? ""); const [to, setTo] = useState(initial?.to_account_id ?? accounts.find((a) => a.id !== from)?.id ?? ""); const [amount, setAmount] = useState(initial ? String(initial.amount) : ""); const [date, setDate] = useState(initial?.date ?? todayISO()); const [note, setNote] = useState(initial?.note ?? ""); async function save() { const n = Number(amount); if (!from || !to || from === to) return toast.error("Choose two different accounts."); if (!Number.isFinite(n) || n <= 0) return toast.error("Enter an amount greater than 0."); const row = { from_account_id: from, to_account_id: to, amount: n, date, note: note.trim() || null }; const { error } = initial ? await supabase.from("transfers").update(row).eq("id", initial.id) : await supabase.from("transfers").insert(row); if (error) return toast.error(friendlyError(error)); invalidate(); onDone(); } return <div className="grid gap-3"><Field label="From"><AccountSelect value={from} onChange={setFrom} accounts={accounts} /></Field><Field label="To"><AccountSelect value={to} onChange={setTo} accounts={accounts} /></Field><Field label="Amount"><Input type="number" min="0.01" step="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} /></Field><Field label="Date"><Input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></Field><Field label="Note"><Input value={note} maxLength={200} onChange={(e) => setNote(e.target.value)} /></Field><Button onClick={save}>{initial ? "Save changes" : "Add transfer"}</Button></div>; }
function AccountSelect({ value, onChange, accounts }: { value: string; onChange: (v: string) => void; accounts: Account[] }) { return <Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{accounts.map((a) => <SelectItem key={a.id} value={a.id}>{a.name}</SelectItem>)}</SelectContent></Select>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="grid gap-1.5"><Label>{label}</Label>{children}</div>; } function Metric({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="font-semibold">{value}</p></div>; } function Empty({ text }: { text: string }) { return <div className="rounded-3xl border bg-card p-10 text-center text-sm text-muted-foreground shadow-soft">{text}</div>; }