import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { Pencil, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/PageHeader";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { supabase } from "@/integrations/supabase/client";
import { categoriesQuery, friendlyError, recurringItemsQuery, useInvalidateData, type RecurringItem } from "@/lib/data";
import { recurringTotals, type RecurringFrequency } from "@/lib/engine";
import { dateLabel, formatMoney, monthLabel, todayISO } from "@/lib/format";
import { profileQuery } from "@/lib/profile";

export const Route = createFileRoute("/_authenticated/_app/recurring")({ head: () => ({ meta: [{ title: "Recurring Payments — Halal Budget Planner" }, { name: "description", content: "Track repeating payments, due dates and monthly set-asides." }, { property: "og:title", content: "Recurring Payments — Halal Budget Planner" }, { property: "og:description", content: "Track repeating payments, due dates and monthly set-asides." }] }), component: RecurringPage });
const frequencies: RecurringFrequency[] = ["Monthly", "Quarterly", "Half-yearly", "Yearly", "One-time"]; const NONE = "__none";

function RecurringPage() { const { data: profile } = useQuery(profileQuery); const { data: items = [] } = useQuery(recurringItemsQuery); const { data: categories = [] } = useQuery(categoriesQuery); const invalidate = useInvalidateData(); const [editing, setEditing] = useState<RecurringItem | "new" | null>(null); const cur = profile?.currency ?? "USD"; const selected = profile?.selected_month.slice(0, 7) ?? todayISO().slice(0, 7); const totals = recurringTotals(items.map((x) => ({ ...x, amount: Number(x.amount) })), todayISO(), selected); const monthly = totals.reduce((s, x) => s + x.monthlySetAside, 0); const categoryNames = useMemo(() => new Map(categories.map((c) => [c.id, c.name])), [categories]); async function remove(item: RecurringItem) { if (!confirm(`Delete recurring payment "${item.name}"?`)) return; const { error } = await supabase.from("recurring_items").delete().eq("id", item.id); if (error) return toast.error(friendlyError(error)); invalidate(); }
  return <><PageHeader eyebrow="Regular payments" title="Recurring Payments" actions={<Button variant="secondary" size="sm" onClick={() => setEditing("new")} disabled={items.length >= 50}><Plus /> Add payment</Button>} /><main className="relative mx-auto -mt-6 flex max-w-6xl flex-col gap-5 px-5 pb-24 md:px-10"><div className="grid gap-3 sm:grid-cols-2"><Stat label="Total monthly equivalent" value={formatMoney(monthly, cur)} /><Stat label={`Due in ${monthLabel(selected)}`} value={String(totals.filter((x) => x.dueInSelectedMonth).length)} /></div>{totals.length === 0 ? <div className="rounded-3xl border bg-card p-10 text-center text-sm text-muted-foreground shadow-soft">Add bills and other payments that repeat.</div> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{totals.map((total) => { const raw = items.find((x) => x.id === total.item.id); return <article key={total.item.id} className="rounded-3xl border bg-card p-5 shadow-soft"><div className="flex justify-between gap-3"><div><p className="text-xs uppercase text-muted-foreground">{total.item.frequency}</p><h2 className="mt-1 text-xl">{total.item.name}</h2></div><div className="flex"><Button size="icon" variant="ghost" aria-label={`Edit ${total.item.name}`} onClick={() => raw && setEditing(raw)}><Pencil /></Button><Button size="icon" variant="ghost" className="hover:text-destructive" aria-label={`Delete ${total.item.name}`} onClick={() => raw && remove(raw)}><Trash2 /></Button></div></div><p className="mt-4 text-2xl font-bold">{formatMoney(total.item.amount, cur)}</p><p className="text-xs text-muted-foreground">{total.item.category_id ? categoryNames.get(total.item.category_id) ?? "Unknown category" : "No category"}</p><div className="mt-4 grid grid-cols-2 gap-3"><Metric label="Next due" value={total.nextDue ? dateLabel(total.nextDue) : "—"} /><Metric label="Days until" value={total.daysUntil == null ? "—" : String(total.daysUntil)} /><Metric label="Status" value={total.status} /><Metric label="Monthly set-aside" value={formatMoney(total.monthlySetAside, cur)} /></div><p className={`mt-4 rounded-2xl p-3 text-sm font-semibold ${total.dueInSelectedMonth ? "bg-accent/25 text-accent-foreground" : "bg-muted text-muted-foreground"}`}>{total.dueInSelectedMonth ? `Due in ${monthLabel(selected)}` : `Not due in ${monthLabel(selected)}`}</p></article>; })}</div>}</main><Dialog open={editing != null} onOpenChange={(o) => !o && setEditing(null)}><DialogContent><DialogHeader><DialogTitle>{editing === "new" ? "Add recurring payment" : "Edit recurring payment"}</DialogTitle></DialogHeader>{editing && <RecurringForm initial={editing === "new" ? undefined : editing} categories={categories} onDone={() => setEditing(null)} />}</DialogContent></Dialog></>;
}
function RecurringForm({ initial, categories, onDone }: { initial?: RecurringItem; categories: Awaited<ReturnType<typeof categoriesQuery.queryFn>>; onDone: () => void }) { const invalidate = useInvalidateData(); const [name, setName] = useState(initial?.name ?? ""); const [amount, setAmount] = useState(initial ? String(initial.amount) : ""); const [frequency, setFrequency] = useState<RecurringFrequency>(initial?.frequency ?? "Monthly"); const [date, setDate] = useState(initial?.first_due_date ?? todayISO()); const [category, setCategory] = useState(initial?.category_id ?? NONE); const [active, setActive] = useState(initial?.active ?? true); async function save() { const n = Number(amount); if (!name.trim()) return toast.error("Enter a payment name."); if (!Number.isFinite(n) || n <= 0) return toast.error("Enter an amount greater than 0."); const row = { name: name.trim(), amount: n, frequency, first_due_date: date, category_id: category === NONE ? null : category, active }; const { error } = initial ? await supabase.from("recurring_items").update(row).eq("id", initial.id) : await supabase.from("recurring_items").insert(row); if (error) return toast.error(friendlyError(error)); invalidate(); onDone(); } return <div className="grid gap-3"><Field label="Name"><Input value={name} onChange={(e) => setName(e.target.value)} autoFocus /></Field><Field label="Amount"><Input type="number" min="0.01" step="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} /></Field><Field label="Frequency"><Select value={frequency} onValueChange={(v) => setFrequency(v as RecurringFrequency)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{frequencies.map((f) => <SelectItem key={f} value={f}>{f}</SelectItem>)}</SelectContent></Select></Field><Field label="First due date"><Input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></Field><Field label="Category"><Select value={category} onValueChange={setCategory}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value={NONE}>No category</SelectItem>{categories.map((c) => <SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></Field><div className="flex items-center justify-between rounded-2xl bg-muted p-4"><Label htmlFor="active-payment">Active</Label><Switch id="active-payment" checked={active} onCheckedChange={setActive} /></div><Button onClick={save}>{initial ? "Save changes" : "Add payment"}</Button></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="grid gap-1.5"><Label>{label}</Label>{children}</div>; } function Metric({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="font-semibold">{value}</p></div>; } function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-3xl border bg-card p-5 shadow-soft"><p className="text-xs font-semibold uppercase text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>; }